"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";

/**
 * Botanical statement section: a large word with the aloe both behind AND in
 * front of it, so the leaves interleave with the letters.
 *
 * Two layers of the same photograph, generated by make-aloe-layers.py:
 *   /aloe-back.jpg   the untouched plate, behind the type
 *   /aloe-front.png  the plant alone on transparency, over the type
 *
 * They carry identical positioning classes, so the doubled plant lines up
 * exactly and reads as one. Parallax therefore has to move BOTH by the same
 * amount - shifting them independently would show the plant twice.
 */
export default function NourishSection({
  word = "RESTORE",
  caption = ["Skin, treated", "at the root"],
}: {
  word?: string;
  caption?: [string, string];
} = {}) {
  const ref = useRef<HTMLElement>(null);
  const [shown, setShown] = useState(false);
  const [offset, setOffset] = useState(0);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    if (typeof IntersectionObserver === "undefined") {
      const id = requestAnimationFrame(() => setShown(true));
      return () => cancelAnimationFrame(id);
    }

    const io = new IntersectionObserver(
      ([e]) => {
        if (e.isIntersecting) {
          setShown(true);
          io.disconnect();
        }
      },
      { threshold: 0.15 },
    );
    io.observe(el);
    return () => io.disconnect();
  }, []);

  // The plant drifts against the fixed type as the section crosses the viewport.
  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const el = ref.current;
    if (!el) return;

    let frame = 0;
    const onScroll = () => {
      if (frame) return;
      frame = requestAnimationFrame(() => {
        frame = 0;
        const r = el.getBoundingClientRect();
        const p = (window.innerHeight - r.top) / (window.innerHeight + r.height);
        setOffset(Math.max(-1, Math.min(1, p * 2 - 1)));
      });
    };
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => {
      window.removeEventListener("scroll", onScroll);
      if (frame) cancelAnimationFrame(frame);
    };
  }, []);

  // Shared so both plant layers stay pixel-aligned.
  const plate = "object-cover object-bottom";
  const rise = shown ? "translate-y-0 opacity-100" : "translate-y-16 opacity-0";
  const drift = { transform: `translateY(${offset * 18}px)` };

  return (
    <section
      ref={ref}
      aria-label={word}
      className="relative isolate min-h-[26rem] overflow-hidden bg-[#f1ede7] sm:min-h-[34rem] lg:min-h-[42rem]"
    >
      {/* Behind the word */}
      <div
        aria-hidden="true"
        className={`absolute inset-0 transition-all duration-[1400ms] ease-out ${rise}`}
      >
        <div className="h-full w-full" style={drift}>
          <Image src="/aloe-back.jpg" alt="" fill sizes="100vw" className={plate} />
        </div>
      </div>

      {/* The word */}
      <div className="absolute inset-x-0 top-[20%] px-6 sm:top-[22%]">
        <h2 className="text-center">
          <span className="sr-only">{word}</span>
          <span
            aria-hidden="true"
            className="flex justify-center font-display font-normal uppercase leading-none tracking-[0.02em] text-forest"
          >
            {word.split("").map((letter, i) => (
              <span
                key={i}
                className={`inline-block text-[3rem] transition-all duration-[1000ms] ease-out sm:text-[5.5rem] lg:text-[8.5rem] ${
                  shown ? "translate-y-0 opacity-100" : "translate-y-6 opacity-0"
                }`}
                style={{ transitionDelay: `${180 + i * 80}ms` }}
              >
                {letter}
              </span>
            ))}
          </span>
        </h2>

        {/* Caption, set left as in the reference */}
        <div
          className={`container-page mt-8 transition-all duration-1000 ease-out sm:mt-12 ${
            shown ? "translate-y-0 opacity-100" : "translate-y-4 opacity-0"
          }`}
          style={{ transitionDelay: `${180 + word.length * 80 + 120}ms` }}
        >
          <p className="text-[0.7rem] font-medium uppercase leading-[1.9] tracking-[0.24em] text-forest/85 sm:text-xs">
            {caption[0]}
            <br />
            {caption[1]}
          </p>
          <span aria-hidden="true" className="mt-4 block h-px w-14 bg-forest/35" />
        </div>
      </div>

      {/* In front of the word - this is what creates the depth */}
      <div
        aria-hidden="true"
        className={`pointer-events-none absolute inset-0 transition-all duration-[1400ms] ease-out ${rise}`}
      >
        <div className="h-full w-full" style={drift}>
          <Image src="/aloe-front.png" alt="" fill sizes="100vw" className={plate} />
        </div>
      </div>
    </section>
  );
}
